Tarzan Pre-2.0 Trunk Build: TarzanCore::authenticate
$account_id
$adjust_offset
$api_version
$assoc_id
$key
$request_class
$response_class
$secret_key
$service
$util
$utilities_class
__construct
adjust_offset
authenticate
set_request_class
set_response_class
set_utilities_class
TarzanCore::authenticate ($ action, $ opt = null, $ queue_url = null, $ message = null)
Authenticate
Authenticates a connection to AWS and is used by EC2, SQS, and SimpleDB. This method is not intended to be manually called. Instead it is called by the other functions on a per-use basis.
private
Parameters:
string $action (Required) Indicates the action to perform.
array $opt (Optional) Associative array of parameters for authenticating. See the individual methods for allowed keys.
string $queue_url (Optional) The URL of the queue to perform the action on.
string $message (Optional) This parameter is only used by the send_message() method.
Returns:
object A TarzanHTTPResponse response object.
See also:
http://docs.amazonwebservices.com/AWSSimpleQueueService/2008-01-01/SQSDeveloperGuide/Query_QueryAuth.html
Reimplemented in AmazonS3.
Definition at line 301 of file tarzan.class.php.
References adjust_offset().
Referenced by AmazonEC2::authorize_security_group_ingress(), AmazonEC2::confirm_product_instance(), AmazonSDB::create_domain(), AmazonEC2::create_key_pair(), AmazonSQS::create_queue(), AmazonEC2::create_security_group(), AmazonSDB::delete_attributes(), AmazonSDB::delete_domain(), AmazonEC2::delete_key_pair(), AmazonSQS::delete_message(), AmazonSQS::delete_queue(), AmazonEC2::delete_security_group(), AmazonEC2::deregister_image(), AmazonEC2::describe_availability_zones(), AmazonEC2::describe_image_attribute(), AmazonEC2::describe_images(), AmazonEC2::describe_instances(), AmazonEC2::describe_key_pairs(), AmazonEC2::describe_security_groups(), AmazonSDB::get_attributes(), AmazonSQS::get_queue_attributes(), AmazonSQS::get_queue_size(), AmazonSDB::list_domains(), AmazonSQS::list_queues(), AmazonEC2::modify_image_attribute(), AmazonSDB::put_attributes(), AmazonSDB::query(), AmazonSQS::receive_message(), AmazonEC2::register_image(), AmazonEC2::reset_image_attribute(), AmazonEC2::revoke_security_group_ingress(), AmazonEC2::run_instances(), AmazonSQS::send_message(), AmazonSQS::set_queue_attributes(), and AmazonEC2::terminate_instances().
        {
                // Manage the key-value pairs that are used in the query.
                $query['Action'] = $action;
                $query['AWSAccessKeyId'] = $this->key;
                $query['SignatureVersion'] = 1;
                $query['Timestamp'] = gmdate(DATE_AWS_ISO8601, time() + $this->adjust_offset);
                $query['Version'] = $this->api_version;
                // Merge in any options that were passed in
                if (is_array($opt))
                {
                        $query = array_merge($query, $opt);
                }
                // Do a case-insensitive, natural order sort on the array keys.
                uksort($query, 'strnatcasecmp');
                // Create the string that needs to be hashed.
                $sign_query = $this->util->to_signable_string($query);
                // Hash the AWS secret key and generate a signature for the request.
                $query['Signature'] = $this->util->hex_to_base64(hash_hmac('sha1', $sign_query, $this->secret_key));
                // Generate the querystring from $query
                $querystring = $this->util->to_query_string($query);
                // Compose the request.
                $request_url = $queue_url . '?' . $querystring;
                $request =& new $this->request_class($request_url);
                // Tweak some things if we have a message (i.e. AmazonSQS::send_message()).
                if ($message)
                {
                        $request->addHeader('Content-Type', 'text/plain');
                        $request->setMethod(HTTP_POST);
                        $request->setBody($message);
                }
                // If we have a "true" value for returnCurlHandle, do that instead of completing the request.
                if (isset($opt['returnCurlHandle']))
                {
                        return $request->prepRequest();
                }
                // Send!
                $request->sendRequest();
                // Prepare the response.
                $headers = $request->getResponseHeader();
                $headers['x-tarzan-requesturl'] = $request_url;
                $headers['x-tarzan-stringtosign'] = $sign_query;
                if ($message) $headers['x-tarzan-body'] = $message;
                $data = new $this->response_class($headers, $request->getResponseBody(), $request->getResponseCode());
                // Return!
                return $data;
        }