Tarzan Pre-2.0 Trunk Build: AmazonS3::delete_all_objects
$request_url
$vhost
__construct
authenticate
copy_bucket
copy_object
create_bucket
create_object
delete_all_objects
delete_bucket
delete_object
duplicate_object
get_bucket
get_bucket_acl
get_bucket_filesize
get_bucket_list
get_bucket_locale
get_bucket_size
get_logs
get_object
get_object_acl
get_object_filesize
get_object_list
get_object_url
get_torrent_url
head_bucket
head_object
if_bucket_exists
if_object_exists
list_buckets
list_objects
move_object
rename_bucket
rename_object
set_bucket_acl
set_logging_permissions
set_object_acl
set_vhost
store_remote_file
toggle_logging
AmazonS3::delete_all_objects ($ bucket, $ pcre = S3_PCRE_ALL)
Delete All Objects
Delete all of the objects inside the specified bucket.
public
Parameters:
string $bucket (Required) The name of the bucket to be used.
string $pcre (Optional) PCRE regular expression to match filenames by. Defaults to S3_PCRE_ALL.
Returns:
boolean Determines the success of deleting all files.
<?php
require_once('tarzan.class.php');
/**
 * Instantiate a new AmazonS3 object using the settings from the config.inc.php file.
 */
$s3 = new AmazonS3();
/**
 * Delete all objects in a bucket.
 */
$delete = $s3->delete_all_objects('warpshare.test.eu');
?>
See also:
delete_object
Definition at line 974 of file s3.class.php.
References delete_object(), and get_object_list().
Referenced by delete_bucket().
        {
                // Collect all matches
                $list = $this->get_object_list($bucket, array('pcre', $pcre));
                // As long as we have at least one match...
                if (count($list) > 0)
                {
                        // Hold CURL handles
                        $handles = array();
                        // Go through all of the items and delete them.
                        foreach ($list as $item)
{
                                $handles[] = $this->delete_object($bucket, $item, true);
                        }
                        $request = new $this->request_class(null);
                        return $request->sendMultiRequest($handles);
                }
                return false;
        }