Tarzan Pre-2.0 Trunk Build: AmazonS3::authenticate
$request_url
$vhost
__construct
authenticate
copy_bucket
copy_object
create_bucket
create_object
delete_all_objects
delete_bucket
delete_object
duplicate_object
get_bucket
get_bucket_acl
get_bucket_filesize
get_bucket_list
get_bucket_locale
get_bucket_size
get_logs
get_object
get_object_acl
get_object_filesize
get_object_list
get_object_url
get_torrent_url
head_bucket
head_object
if_bucket_exists
if_object_exists
list_buckets
list_objects
move_object
rename_bucket
rename_object
set_bucket_acl
set_logging_permissions
set_object_acl
set_vhost
store_remote_file
toggle_logging
AmazonS3::authenticate ($ bucket, $ opt = null, $ location = null, $ redirects = 0)
Authenticate
Authenticates a connection to S3.
public
Parameters:
string $bucket (Required) The name of the bucket to be used.
array $opt (Optional) Associative array of parameters for authenticating. See the individual methods for allowed keys.
string $location (Do Not Use) Used internally by this function on occasions when S3 returns a redirect code and it needs to call itself recursively.
integer $redirects (Do Not Use) Used internally by this function on occasions when S3 returns a redirect code and it needs to call itself recursively.
Returns:
TarzanHTTPResponse
See also:
http://docs.amazonwebservices.com/AmazonS3/2006-03-01/RESTAuthentication.html
Reimplemented from TarzanCore.
Definition at line 115 of file s3.class.php.
References TarzanCore::adjust_offset().
Referenced by copy_object(), create_bucket(), create_object(), delete_bucket(), delete_object(), get_bucket_acl(), get_bucket_locale(), get_logs(), get_object(), get_object_acl(), get_object_url(), head_bucket(), head_object(), list_buckets(), list_objects(), set_bucket_acl(), and set_object_acl().
        {
                // If nothing was passed in, don't do anything.
                if (!$opt)
                {
                        return false;
                }
                else
                {
                        // Set default values
                        $bucket = strtolower($bucket);
                        $acl = null;
                        $body = null;
                        $contentType = null;
                        $delimiter = null;
                        $filename = null;
                        $marker = null;
                        $maxKeys = null;
                        $method = null;
                        $prefix = null;
                        $verb = null;
                        $lastmodified = null;
                        $etag = null;
                        $qsa = null;
                        $md5 = null;
                        $meta = null;
                        $hmeta = null;
                        $range = null;
                        $returnCurlHandle = null;
                        // Break the array into individual variables, while storing the original.
                        $_opt = $opt;
                        extract($opt);
                        $filename = rawurlencode($filename);
                        // Set hostname
                        if ($this->vhost)
{
                                $hostname = $this->vhost;
                        }
                        elseif ($method == 'list_buckets')
{
                                $hostname = 's3.amazonaws.com';
                        }
                        else
{
                                $hostname = $bucket . '.s3.amazonaws.com';
                        }
                        // Get the UTC timestamp in RFC 2616 format
                        $since_epoch = time() + $this->adjust_offset;
                        $httpDate = gmdate(DATE_AWS_RFC2616, $since_epoch);
                        // Generate the request string
                        $request = '';
                        // Append additional parameters
                        $request .= '/' . $filename;
                        // List Object settings
                        if ($method == 'list_objects')
{
                                if (isset($prefix) && !empty($prefix))
{
                                        $request = '/?prefix=' . $prefix;
                                }
                                else if (isset($marker) && !empty($marker))
{
                                        $request = '/?marker=' . $marker;
                                }
                                else if (isset($maxKeys) && !empty($maxKeys))
{
                                        $request = '/?max-keys=' . $maxKeys;
                                }
                                else if (isset($delimiter) && !empty($delimiter))
{
                                        $request = '/?delimiter=' . $delimiter;
                                }
                        }
                        // Logging
                        elseif ($method == 'get_logs')
{
                                $request .= '?logging';
                                $filename .= '?logging';
                        }
                        // Get Bucket Locale settings
                        elseif ($method == 'get_bucket_locale')
{
                                $request = '/?location';
                                $filename = '?location';
                        }
                        // Add ACL stuff if we're getting/setting ACL preferences.
                        elseif ($method == 'get_bucket_acl' || $method == 'get_object_acl')
{
                                $request .= '?acl';
                                $filename .= '?acl';
                        }
                        if (!$request == '/')
{
                                $request = '/' . $request;
                        }
                        // Prepare the request.
                        if ($location)
{
                                $this->request_url = $location;
                        }
                        else
{
                                $this->request_url = 'http://' . $hostname . $request;
                        }
                        // Instantiate the request class
                        $req = new $this->request_class($this->request_url);
                        // Do we have a verb?
                        if (isset($verb) && !empty($verb))
{
                                $req->setMethod($verb);
                        }
                        // Do we have a contentType?
                        if (isset($contentType) && !empty($contentType))
{
                                $req->addHeader('Content-Type', $contentType);
                        }
                        else if ($verb == HTTP_PUT) // Set a default value for HTTP_PUT
{
                                $contentType = 'application/x-www-form-urlencoded';
                        }
                        // Do we have a date?
                        if (isset($httpDate) && !empty($httpDate))
{
                                $req->addHeader("Date", $httpDate);
                        }
                        // Do we have ACL settings? (Optional in signed string)
                        if (isset($acl) && !empty($acl))
{
                                $req->addHeader("x-amz-acl", $acl);
                                $acl = 'x-amz-acl:' . $acl . "\n";
                        }
                        // Do we have COPY settings?
                        if ($method == 'copy_object')
{
                                $acl .= 'x-amz-copy-source:/' . $sourceBucket . '/' . $sourceObject . "\n";
                                $req->addHeader('x-amz-copy-source', '/' . $sourceBucket . '/' . $sourceObject);
                        }
                        // Are we checking for changes?
                        if ($lastmodified && $etag)
{
                                $req->addHeader('If-Modified-Since', $lastmodified);
                                $req->addHeader('If-None-Match', $etag);
                        }
                        // Partial content range
                        if ($range)
{
                                $req->addHeader('Range', 'bytes=' . $range);
                        }
                        // Add a body if we're creating
                        if ($method == 'create_object' || $method == 'create_bucket')
{
                                if (isset($body) && !empty($body))
{
                                        $req->setBody($body);
                                        $md5 = $this->util->hex_to_base64(md5($body));
                                        $req->addHeader('Content-MD5', $md5);
                                }
                                // Add any meta headers.
                                if ($meta)
{
                                        uksort($meta, 'strnatcasecmp');
                                        foreach ($meta as $k => $v)
{
                                                $req->addHeader('x-amz-meta-' . strtolower($k), $v);
                                                $hmeta .= 'x-amz-meta-' . strtolower($k) . ':' . $v . "\n";
                                        }
                                }
                        }
                        // Data that will be "signed".
                        $filename = '/' . $filename;
                        // If we're listing buckets, there is no filename value.
                        if ($method == 'list_buckets')
{
                                $filename = '';
                        }
                        if ($qsa)
{
                                // Prepare the string to sign
                                $stringToSign = "$verb\n$md5\n$contentType\n$since_epoch\n$acl$hmeta/$bucket$filename";
                        }
                        else
{
                                // Prepare the string to sign
                                $stringToSign = "$verb\n$md5\n$contentType\n$httpDate\n$acl$hmeta/$bucket$filename";
                        }
                        // Hash the AWS secret key and generate a signature for the request.
                        $signature = $this->util->hex_to_base64(hash_hmac('sha1', $stringToSign, $this->secret_key));
                        // Pass the developer key and signature
                        $req->addHeader("Authorization", "AWS " . $this->key . ":" . $signature);
                        // If we have a "true" value for returnCurlHandle, do that instead of completing the request.
                        if ($returnCurlHandle)
{
                                return $req->prepRequest();
                        }
                        // Are we getting a Query String Auth?
                        if ($qsa)
{
                                return array(
                                        'bucket' => $bucket,
                                        'filename' => $filename,
                                        'key' => $this->key,
                                        'expires' => $since_epoch,
                                        'signature' => $signature,
                                );
                        }
                        // Send!
                        $req->sendRequest();
                        // Prepare the response.
                        $headers = $req->getResponseHeader();
                        $headers['x-tarzan-redirects'] = $redirects;
                        $headers['x-tarzan-requesturl'] = $this->request_url;
                        $headers['x-tarzan-stringtosign'] = $stringToSign;
                        $headers['x-tarzan-requestheaders'] = $req->request_headers;
                        $data = new $this->response_class($headers, $req->getResponseBody(), $req->getResponseCode());
                        // Did Amazon tell us to redirect? Typically happens for multiple rapid requests EU datacenters.
                        // @see http://docs.amazonwebservices.com/AmazonS3/2006-03-01/Redirects.html
                        if ((int) $req->getResponseCode() == 307) // Temporary redirect to new endpoint.
{
                                $redirects++;
                                $data = $this->authenticate($bucket,
                                        $_opt,
                                        $headers['location'],
                                        $redirects);
                        }
                        // Return!
                        return $data;
                }
        }