Tarzan Pre-2.0 Trunk Build: AmazonAAWS::authenticate
__construct
authenticate
browse_node_lookup
cart_add
cart_clear
cart_create
cart_get
cart_modify
customer_content_lookup
customer_content_search
help
item_lookup
item_search
list_lookup
list_search
seller_listing_lookup
seller_listing_search
seller_lookup
similarity_lookup
tag_lookup
transaction_lookup
AmazonAAWS::authenticate ($ action, $ opt = null, $ locale = AAWS_LOCALE_US)
Authenticate
Construct a URL to request from Amazon, request it, and return a formatted response.
public
Parameters:
string $action (Required) Indicates the action to perform.
array $opt (Optional) Settings to use for the request.
string $locale (Optional) Which Amazon-supported locale do we use?
Returns:
TarzanHTTPResponse
Definition at line 87 of file aaws.class.php.
Referenced by browse_node_lookup(), cart_add(), customer_content_lookup(), customer_content_search(), help(), item_lookup(), item_search(), list_lookup(), and list_search().
        {
                // Determine the hostname
                switch ($locale)
                {
                        // United Kingdom
                        case AAWS_LOCALE_UK:
                                $hostname = 'http://ecs.amazonaws.co.uk/';
                                break;
                        // Canada
                        case AAWS_LOCALE_CANADA:
                                $hostname = 'http://ecs.amazonaws.ca/';
                                break;
                        // France
                        case AAWS_LOCALE_FRANCE:
                                $hostname = 'http://ecs.amazonaws.fr/';
                                break;
                        // Germany
                        case AAWS_LOCALE_GERMANY:
                                $hostname = 'http://ecs.amazonaws.de/';
                                break;
                        // Japan
                        case AAWS_LOCALE_JAPAN:
                                $hostname = 'http://ecs.amazonaws.jp/';
                                break;
                        // Default to United States
                        default:
                                $hostname = 'http://ecs.amazonaws.com/';
                                break;
                }
                // Send the request to the service.
                $request_url = $hostname . 'onca/xml?Service=AWSECommerceService&AWSAccessKeyId=' . $this->key . '&Operation=' . $action . '&' . $this->util->to_query_string($opt);
                $request =& new $this->request_class($request_url);
                $request->sendRequest();
                // Prepare the response.
                $headers = $request->getResponseHeader();
                $headers['x-tarzan-requesturl'] = $request_url;
                $headers['x-tarzan-httpstatus'] = $request->getResponseCode();
                $data = new $this->response_class($headers, $request->getResponseBody(), $request->getResponseCode());
                // Return!
                return $data;
        }