Tarzan Pre-2.0 Trunk Build: AmazonS3::copy_bucket
$request_url
$vhost
__construct
authenticate
copy_bucket
copy_object
create_bucket
create_object
delete_all_objects
delete_bucket
delete_object
duplicate_object
get_bucket
get_bucket_acl
get_bucket_filesize
get_bucket_list
get_bucket_locale
get_bucket_size
get_logs
get_object
get_object_acl
get_object_filesize
get_object_list
get_object_url
get_torrent_url
head_bucket
head_object
if_bucket_exists
if_object_exists
list_buckets
list_objects
move_object
rename_bucket
rename_object
set_bucket_acl
set_logging_permissions
set_object_acl
set_vhost
store_remote_file
toggle_logging
AmazonS3::copy_bucket ($ source_bucket, $ dest_bucket)
Copy Bucket
Copies the contents of a bucket into a new bucket.
public
Parameters:
string $source_bucket (Required) The name of the source bucket.
string $dest_bucket (Required) The name of the destination bucket.
Returns:
TarzanHTTPResponse
<?php
require_once('tarzan.class.php');
/**
 * Instantiate a new AmazonS3 object using the settings from the config.inc.php file.
 */
$s3 = new AmazonS3();
/**
 * Copy the contents of an existing bucket to a newly created bucket.
 */
$copy = $s3->copy_bucket('warpshare.test.eu', 'warpshare.test.eu.backup');
/**
 * Look at the response to navigate through the headers and body of the response.
 * Note that this is an object, not an array, and that the body is a SimpleXML object.
 *
 * http://php.net/manual/en/simplexml.examples.php
 */
echo '<pre>';
print_r($copy);
echo '</pre>';
/**
 * Custom function for displaying which files were successfully copied. Accepts the
 * response from the copy_bucket() method as input.
 */
function list_successful_files($copy_object, $status = 200)
{
        $files = array();
        foreach ($copy_object as $obj)
        {
                if ($obj->isOK($status))
                {
                        $files[] = (string) $obj->header['_info']['url'];
                }
        }
        return $files;
}
/**
 * Example of us calling the new custom function and passing in the copy_object()
 * response to get an array of filenames that were successfully copied.
 */
$files = list_successful_files($copy);
print_r($files);
?>
Definition at line 576 of file s3.class.php.
References copy_object(), create_bucket(), get_bucket_locale(), and get_object_list().
Referenced by rename_bucket().
        {
                // Since S3 can't yet copy across geographical locations, make sure that the new bucket matches the existing bucket.
                $locale = $this->get_bucket_locale($source_bucket);
                switch ($locale->body)
                {
                        case S3_LOCATION_EU:
                                $locale = S3_LOCATION_EU;
                                break;
                        default:
                                $locale = S3_LOCATION_US;
                                break;
                }
                $dest = $this->create_bucket($dest_bucket, $locale);
                if ($dest->isOK())
                {
                        $list = $this->get_object_list($source_bucket);
                        $handles = array();
                        foreach ($list as $item)
{
                                $handles[] = $this->copy_object($source_bucket, $item, $dest_bucket, $item, array(
                                        'acl' => S3_ACL_PRIVATE,
                                        'returnCurlHandle' => true
                                ));
                        }
                        $request = new $this->request_class(null);
                        return $request->sendMultiRequest($handles);
                }
                return false;
        }