Tarzan Pre-2.0 Trunk Build: AmazonS3::get_object_list
$request_url
__construct
authenticate
copy_bucket
copy_object
create_bucket
create_object
delete_all_objects
delete_bucket
delete_object
duplicate_object
get_bucket
get_bucket_acl
get_bucket_filesize
get_bucket_list
get_bucket_locale
get_bucket_size
get_object
get_object_acl
get_object_filesize
get_object_list
head_bucket
head_object
if_bucket_exists
if_object_exists
list_buckets
list_objects
move_object
rename_bucket
rename_object
set_bucket_acl
set_object_acl
store_remote_file
AmazonS3::get_object_list ($ bucket, $ opt = null)
Get Object List
ONLY lists the object filenames from a bucket.
public
Parameters:
string $bucket (Required) The name of the bucket to be used.
array $opt (Optional) Associative array of parameters which can have the following keys:
string prefix - (Optional) Restricts the response to only contain results that begin with the specified prefix.
string marker - (Optional) It restricts the response to only contain results that occur alphabetically after the value of marker.
string maxKeys - (Optional) Limits the number of results returned in response to your query. Will return no more than this number of results, but possibly less.
string delimiter - (Optional) Unicode string parameter. Keys that contain the same string between the prefix and the first occurrence of the delimiter will be rolled up into a single result element in the CommonPrefixes collection.
string pcre - (Optional) A Perl-Compatible Regular Expression (PCRE) to filter the filenames against. This is applied AFTER any native S3 filtering from 'prefix', 'marker', 'maxKeys', or 'delimiter'.
Returns:
array
See also:
list_objects
Definition at line 891 of file s3.class.php.
References list_objects().
Referenced by copy_bucket(), delete_all_objects(), and get_bucket_size().
        {
                // Set some default values
                $filenames = array();
                $pcre = null;
                // Get a list of files.
                $list = $this->list_objects($bucket, $opt);
                // Extract the options
                if ($opt)
                {
                        extract($opt);
                }
                // If we have a PCRE regex, store it.
                if ($pcre)
                {
                        // Loop through and find the filenames.
                        foreach ($list->body->Contents as $file)
{
                                $file = (string) $file->Key;
                                if (preg_match($pcre, $file))
{
                                        $filenames[] = $file;
                                }
                        }
                }
                else
                {
                        // Loop through and find the filenames.
                        foreach ($list->body->Contents as $file)
{
                                $filenames[] = (string) $file->Key;
                        }
                }
                return (count($filenames) > 0) ? $filenames : null;
        }