Tarzan Pre-2.0 Trunk Build: AmazonS3::get_object_url
$request_url
$vhost
__construct
authenticate
copy_bucket
copy_object
create_bucket
create_object
delete_all_objects
delete_bucket
delete_object
duplicate_object
get_bucket
get_bucket_acl
get_bucket_filesize
get_bucket_list
get_bucket_locale
get_bucket_size
get_logs
get_object
get_object_acl
get_object_filesize
get_object_list
get_object_url
get_torrent_url
head_bucket
head_object
if_bucket_exists
if_object_exists
list_buckets
list_objects
move_object
rename_bucket
rename_object
set_bucket_acl
set_logging_permissions
set_object_acl
set_vhost
store_remote_file
toggle_logging
AmazonS3::get_object_url ($ bucket, $ filename, $ qsa = 0, $ torrent = false)
Get Object URL
Gets the URL for the file.
public
Parameters:
string $bucket (Required) The name of the bucket to be used. Pass null if using AmazonS3::set_vhost().
string $filename (Required) The filename for the content.
integer $qsa (Optional) This doubles as a boolean (do you want to use Query String Authentication?) and an integer (how many seconds from now should this authentication work?). Defaults to 0/false.
boolean $torrent (Optional) Whether to return the torrent version of the URL or not. Defaults to false.
Returns:
string The file URL, with authentication parameters if requested.
<?php
require_once('tarzan.class.php');
/**
 * Instantiate a new AmazonS3 object using the settings from the config.inc.php file.
 */
$s3 = new AmazonS3();
/**
 * Display the URL for accessing this file in this bucket.
 */
echo $s3->get_object_url('warpshare.test.eu', 'sample.txt');
?>
Definition at line 1426 of file s3.class.php.
References TarzanCore::adjust_offset(), and authenticate().
Referenced by get_torrent_url().
        {
                if ($qsa)
                {
                        // Add this to our request
                        $opt = array();
                        $opt['verb'] = HTTP_GET;
                        $opt['method'] = 'get_object_url';
                        $opt['filename'] = $filename . (($torrent) ? '?torrent' : '');
                        $opt['qsa'] = $qsa;
                        // Adjust the clock
                        $old_offset = $this->adjust_offset;
                        $this->adjust_offset($qsa);
                        // Authenticate to S3
                        $data = $this->authenticate($bucket, $opt);
                        // Reset the clock
                        $this->adjust_offset = $old_offset;
                        if ($this->vhost)
{
                                return 'http://' . $this->vhost . $data['filename'] . ((!$torrent) ? '?' : '&') . 'AWSAccessKeyId=' . $data['key'] . '&Expires=' . $data['expires'] . '&Signature=' . rawurlencode($data['signature']);
                        }
                        return 'http://' . $data['bucket'] . '.s3.amazonaws.com' . $data['filename'] . ((!$torrent) ? '?' : '&') . 'AWSAccessKeyId=' . $data['key'] . '&Expires=' . $data['expires'] . '&Signature=' . rawurlencode($data['signature']);
                }
                else
                {
                        // If we're using a virtual host, use that instead.
                        if ($this->vhost)
{
                                return 'http://' . $this->vhost . '/' . $filename . (($torrent) ? '?torrent' : '');
                        }
                        return 'http://' . $bucket . '.s3.amazonaws.com/' . $filename . (($torrent) ? '?torrent' : '');
                }
        }