Tarzan Pre-2.0 Trunk Build: AmazonS3::head_object
$request_url
__construct
authenticate
copy_bucket
copy_object
create_bucket
create_object
delete_all_objects
delete_bucket
delete_object
duplicate_object
get_bucket
get_bucket_filesize
get_bucket_list
get_bucket_locale
get_bucket_size
get_object
get_object_filesize
get_object_list
head_bucket
head_object
if_bucket_exists
if_object_exists
list_buckets
list_objects
move_object
rename_bucket
rename_object
store_remote_file
AmazonS3::head_object ($ bucket, $ filename, $ returnCurlHandle = null)
HEAD Object
Reads only the HTTP headers of an object within a bucket.
public
Parameters:
string $bucket (Required) The name of the bucket check.
string $filename (Required) The filename for the content.
boolean $returnCurlHandle (Optional) A private toggle that will return the CURL handle for the request rather than actually completing the request. This is useful for MultiCURL requests.
Returns:
TarzanHTTPResponse
See also:
http://docs.amazonwebservices.com/AmazonS3/2006-03-01/RESTObjectHEAD.html
Definition at line 679 of file s3.class.php.
References authenticate().
Referenced by get_object_filesize(), if_object_exists(), and store_remote_file().
        {
                // Add this to our request
                $opt = array();
                $opt['verb'] = HTTP_HEAD;
                $opt['method'] = 'head_object';
                $opt['filename'] = rawurlencode($filename);
                $opt['returnCurlHandle'] = $returnCurlHandle;
                // Authenticate to S3
                return $this->authenticate($bucket, $opt);
        }