Tarzan: AmazonS3::move_object
$request_url
__construct
authenticate
copy_bucket
copy_object
create_bucket
create_object
delete_all_objects
delete_bucket
delete_object
duplicate_object
get_bucket
get_bucket_filesize
get_bucket_list
get_bucket_locale
get_bucket_size
get_object
get_object_filesize
get_object_list
head_bucket
head_object
if_bucket_exists
if_object_exists
list_buckets
list_objects
move_object
rename_bucket
rename_object
store_remote_file
AmazonS3::move_object ($ source_bucket, $ source_filename, $ dest_bucket, $ dest_filename, $ acl = S3_ACL_PRIVATE)
Move Object
Moves an object to a new location.
public
Parameters:
string $source_bucket (Required) The name of the bucket that contains the source file.
string $source_filename (Required) The source filename that you want to copy.
string $dest_bucket (Required) The name of the bucket that you want to copy the file to.
string $dest_filename (Required) The filename that you want to give to the copy.
string $acl - (Optional) One of the following options: S3_ACL_PRIVATE, S3_ACL_PUBLIC, S3_ACL_OPEN, or S3_ACL_AUTH_READ. Defaults to S3_ACL_PRIVATE.
Todo:
Add support for custom metadata.
Definition at line 945 of file s3.class.php.
References copy_object(), and delete_object().
Referenced by rename_object().
        {
                $copy = $this->copy_object($source_bucket, $source_filename, $dest_bucket, $dest_filename, $acl);
                $del = $this->delete_object($source_bucket, $source_filename);
                return $copy;
        }